# Boolean Indexing

## Array Indexing for changing elements:

In [2]:
# Create a 3x2 array
import numpy as np
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [3]:
# Create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray  as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [4]:
# We can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [5]:
# For short, we could have just used the approach below without the need for the filter
an_array[an_array > 15]

array([21, 22, 31, 32])

In [6]:
an_array[(an_array>20) & (an_array<30)]

array([21, 22])

In [8]:
an_array[an_array % 2 == 0]

array([12, 22, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter. Let's add 100 to all even values.

In [9]:
an_array[an_array % 2 == 0] += 100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]
